include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Container-Scanning.gitlab-ci.yml
  
container_scanning:   
  variables:     
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE    
    CI_APPLICATION_TAG: $CI_COMMIT_REF_SLUG
    
stages:   
  - build   
  - test
  - release   
  - deploy

build_image:
  image: docker:git
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --pull .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

release_image:
  image: docker:git
  stage: release
  services:
    - docker:dind
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

deploy_production:
  image: alpine
  stage: deploy
  environment: production
  only:
    - master
  tags:
    - ccb
  before_script:
    - apk add --no-cache openssh
    - eval "$(ssh-agent -s)"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 ~/.ssh/
    - ssh-keyscan -H 'deflector.cs.hhu.de' > ~/.ssh/known_hosts
  script:
    - ssh root@deflector.cs.hhu.de
