version: '3' #version of docker compose file format

volumes:
  runs-data:
    name: runs
  db-data:
    name: db
services:
  db:
    image: mariadb
    ports:
      - 5555:3306
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - prod.env
  web:
    build: .
    restart: always
    ports:
      - 3333:8080
    depends_on:
      - db
    env_file:
      - prod.env
    volumes:
      - runs-data:/usr/src/pwdsi/data/runs
